version: '3.8'

volumes:
  postgres_data:

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-app
    ports:
      - "${FLASK_PORT}:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    restart: always

  postgres:
    image: postgres:13.1-alpine
    container_name: postgres_flask
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    